name: 'AICF Action'
description: 'Runs AICF via GitHub Actions.'
author: 'AICF Team <aicf@nltgis.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  tfcommand:
    description: TF sub command to run
    required: true
  terraformcloudtoken:
    description: Terraform Cloud Token
    required: true
  fugueenvironmentid:
    description: Fugue Environment ID
    required: true
  fugueclientid:
    description: Fugue Client ID
    required: true
  fugueclientsecret:
    description: Fugue Client secret
    required: true
  cloudprovider:
    description: Cloud provider TF will deploy to
    required: true
  terraformsha256:
    description: Sha256 hash of TF binary
    default: 'be99da1439a60942b8d23f63eba1ea05ff42160744116e84f46fc24f1a8011b6'
    required: true
  terraformversion:
    description: TF version
    default: '0.12.28'
    required: true
  intervalinseconds:
    description: Fugue scan interval
    default: '86400'
    required: true
  regulaversion:
    description: Version of Regula binary
    default: '0.4.0'
    required: true
  opaversion:
    description: Version of Open Policy Agent
    default: '0.22.0'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
