name: 'AICF Action'
description: 'Runs AICF via GitHub Actions.'
author: 'AICF Team <aicf@nltgis.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  tfcommand:
    description: TF sub command to run
    required: true
  terraformcloudtoken:
    description: Terraform Cloud Token
    required: true
  fugueenvironmentid:
    description: Fugue Environment ID
    required: true
  fugueclientid:
    description: Fugue Client ID
    required: true
  fugueclientsecret:
    description: Fugue Client secret
    required: true
  cloudprovider:
    description: Cloud provider TF will deploy to
    required: true
  tf_workdir:
    description: Working directory of terraform files in relation to top level repo directory
    default: 'terraform'
    required: true
  terraformsha256:
    description: Sha256 hash of TF binary
    default: 'a73459d406067ce40a46f026dce610740d368c3b4a3d96591b10c7a577984c2e'
    required: true
  terraformversion:
    description: TF version
    default: '1.0.8'
    required: true
  intervalinseconds:
    description: Fugue scan interval
    default: '86400'
    required: true
  regulaversion:
    description: Version of Regula binary
    default: '2.1.0'
    required: true
  opaversion:
    description: Version of Open Policy Agent
    default: '0.28.0'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
