name: 'AICF Action'
description: 'Runs AICF via GitHub Actions.'
author: 'AICF Team <aicf@nltgis.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  tfcommand:
    description: TF sub command to run
    required: true
  terraformcloudtoken:
    description: Terraform Cloud Token
    required: true
  fugueenvironmentid:
    description: Fugue Environment ID
    required: true
  fugueclientid:
    description: Fugue Client ID
    required: true
  fugueclientsecret:
    description: Fugue Client secret
    required: true
  cloudprovider:
    description: Cloud provider TF will deploy to
    required: true
  tf_workdir:
    description: Working directory of terraform files in relation to top level repo directory
    default: 'terraform'
    required: true
  terraformsha256:
    description: Sha256 hash of TF binary
    default: '281344ed7e2b49b3d6af300b1fe310beed8778c56f3563c4d60e5541c0978f1b'
    required: true
  terraformversion:
    description: TF version
    default: '1.2.5'
    required: true
  intervalinseconds:
    description: Fugue scan interval
    default: '86400'
    required: true
  regulaversion:
    description: Version of Regula binary
    default: '2.8.1'
    required: true
  opaversion:
    description: Version of Open Policy Agent
    default: '0.42.2'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
